### ISSUE TITLE
Page title: A web page must have a title that describes its topic or purpose

### ISSUE THREAD

**Issue by nul800sebastiaan** [umbraco/Umbraco-CMS.Accessibility.Issues#13]
Page title: (Live) Content - a11y-community-team-testproject.euwest01.umbraco.io

**Comment by BatJan** [comment]
@DannyLancaster Was this a genuine issue or is this a leftover "test" issue when we @nul800sebastiaan was figuring out how to configure the board for us? If it's a genuine could you provide some more context about where this issue happens?

**Comment by DannyLancaster** [comment]
Going to close for now as Rachel also confirmed this was previously resolved @BatJan
